# Generated by Django 5.0.3 on 2024-08-10 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apartments", "0003_apartment_house_apartment_lease_end_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analytics_type",
                    models.CharField(
                        choices=[
                            ("occupancy", "Occupancy"),
                            ("finance", "Finance"),
                            ("maintenance", "Maintenance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "recorded_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "related_apartments",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics",
                        to="apartments.apartment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("report_file", models.FileField(upload_to="reports/")),
                ("filters_applied", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Forecasting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("occupancy", "Occupancy"),
                            ("rental_income", "Rental Income"),
                            ("expenses", "Expenses"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "forecasted_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("forecast_date", models.DateTimeField(auto_now_add=True)),
                ("forecast_period", models.CharField(max_length=50)),
                (
                    "related_apartment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forecasts",
                        to="apartments.apartment",
                    ),
                ),
            ],
        ),
    ]
