# Generated by Django 5.0.3 on 2024-08-13 09:29

import building_owners.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_owner_name", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(max_length=254, unique=True)),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[0-9]{3} ?[0-9-]{8,11}$",
                                message="Phone number must be entered in the format: '08012345678' or '+2348012345678'. Up to 15 digits allowed.",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "profile_pics",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="building-owner-profile-pics/",
                        validators=[building_owners.models.validate_image_size],
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "portfolio_size",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "investment_strategy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("mixed_use", "Mixed use"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_owner",
                        to="companies.company",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="building_owner",
                        to="locations.country",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="building_owner",
                        to="locations.state",
                    ),
                ),
            ],
            options={
                "ordering": ["updated"],
            },
        ),
    ]
