# Generated by Django 5.0.3 on 2024-08-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("building_owners", "0003_alter_buildingowner_user"),
        ("companies", "0002_rename_owner_company_user"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingowner",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_owners",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="buildingowner",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_owners",
                to="users.profile",
            ),
        ),
    ]
