# Generated by Django 5.0.3 on 2024-08-13 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "building_owners",
            "0004_alter_buildingowner_company_alter_buildingowner_user",
        ),
        ("locations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingowner",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="building_owners",
                to="locations.country",
            ),
        ),
        migrations.AlterField(
            model_name="buildingowner",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="building_owners",
                to="locations.state",
            ),
        ),
        migrations.AlterField(
            model_name="buildingowner",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="building_owners",
                to="users.profile",
            ),
        ),
    ]
