# Generated by Django 5.0.3 on 2024-08-14 11:44

import building_owners.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("building_owners", "0006_alter_buildingowner_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingowner",
            name="profile_pics",
            field=models.ImageField(
                blank=True,
                default="building-owner-profile-pics/dp.jpg",
                null=True,
                upload_to="building-owner-profile-pics/",
                validators=[building_owners.models.validate_image_size],
            ),
        ),
    ]
