# Generated by Django 5.0.3 on 2024-08-14 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("building_owners", "0007_alter_buildingowner_profile_pics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingowner",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[0-9]{3} ?[0-9-]{8,11}$",
                        message="Phone number must be entered in the format: '08012345678' or '+2348012345678'. Up to 15 digits allowed.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="buildingowner",
            name="profile_pics",
            field=models.ImageField(
                blank=True,
                default="building-owner-profile-pics/dp.jpg",
                null=True,
                upload_to="building-owner-profile-pics/",
            ),
        ),
    ]
