# Generated by Django 5.0.3 on 2024-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("building_owners", "0008_alter_buildingowner_contact_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingowner",
            name="is_visible",
            field=models.BooleanField(default=False),
        ),
    ]
