# Generated by Django 5.0.6 on 2024-07-04 11:26

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "Male"), ("f", "Female")], max_length=50
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("state_of_origin", models.CharField(max_length=50)),
                ("state_of_residence", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("address_1", models.CharField(max_length=200)),
                ("address_2", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
