# Generated by Django 5.0.6 on 2024-07-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=50
            ),
        ),
    ]
