# Generated by Django 5.0.6 on 2024-07-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estate", "0002_registration_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="address_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
