# Generated by Django 5.0.6 on 2024-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estate", "0004_remove_registration_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="password",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
