# Generated by Django 5.0.6 on 2024-07-04 12:21

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estate", "0005_registration_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128,
                region=None,
                validators=[
                    django.core.validators.RegexValidator("^\\d{3}-\\d{3}-\\d{4}$")
                ],
            ),
        ),
    ]
