# Generated by Django 5.0.6 on 2024-07-04 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estate", "0006_alter_registration_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[0-9]{3} ?[0-9-]{8,11}$"
                    )
                ],
            ),
        ),
    ]
