# Generated by Django 5.0.6 on 2024-08-03 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
    ]
