# Generated by Django 5.0.3 on 2024-08-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyers", "0002_buyer_user"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyers",
                to="users.profile",
            ),
        ),
    ]
