# Generated by Django 5.0.3 on 2024-08-13 09:29

import companies.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[0-9]{3} ?[0-9-]{8,11}$",
                                message="Phone number must be entered in the format: '08012345678' or '+2348012345678'. Up to 15 digits allowed.",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("website", models.CharField(blank=True, max_length=200, null=True)),
                ("cac", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="company-logo/default.svg",
                        null=True,
                        upload_to="company-logo/",
                        validators=[companies.models.validate_image_size],
                    ),
                ),
                (
                    "year_founded",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
