# Generated by Django 5.0.6 on 2024-07-19 13:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[0-9]{3} ?[0-9-]{8,11}$"
                            )
                        ],
                    ),
                ),
                ("designation", models.CharField(default="agent", max_length=10)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        default="profile-pics/users-default.png",
                        null=True,
                        upload_to="profile-pics/",
                    ),
                ),
                (
                    "state_of_residence",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("address_1", models.CharField(blank=True, max_length=200, null=True)),
                ("address_2", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "social_github",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "social_twitter",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "social_linkedin",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "social_youtube",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "social_website",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
