# Generated by Django 5.0.3 on 2024-08-14 11:51

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_social_github_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile-pics/dp.jpg",
                null=True,
                upload_to="profile-pics/",
                validators=[users.models.validate_image_size],
            ),
        ),
    ]
