# Generated by Django 5.0.3 on 2024-08-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile-pics/dp.jpg",
                null=True,
                upload_to="profile-pics/",
            ),
        ),
    ]
