# Generated by Django 5.0.3 on 2024-08-14 11:51

import agents.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_alter_agent_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="agents/dp.jpg",
                null=True,
                upload_to="agents/",
                validators=[agents.models.validate_image_size],
            ),
        ),
    ]
