# Generated by Django 5.0.3 on 2024-08-14 11:51

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_alter_tenant_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="tenants-profile-pics/dp.jpg",
                null=True,
                upload_to="tenants-profile-pics/",
                validators=[tenants.models.validate_image_size],
            ),
        ),
    ]
