# Generated by Django 5.0.3 on 2024-08-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                            ("profit_loss", "Profit & Loss"),
                            ("budget", "Budget"),
                        ],
                        max_length=50,
                    ),
                ),
                ("report_date", models.DateField()),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                ("total_income", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("net_profit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="financial_reports/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_date", models.DateField()),
                ("message", models.TextField()),
                ("sent", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[("rent", "Rent"), ("expense", "Expense")],
                        max_length=50,
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt_file",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("online", "Online Payment"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "receipt",
                    models.FileField(blank=True, null=True, upload_to="rent_receipts/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("utilities", "Utilities"),
                            ("taxes", "Taxes"),
                            ("insurance", "Insurance"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="expense_receipts/"
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="apartments.apartment",
                    ),
                ),
            ],
        ),
    ]
