# Generated by Django 5.0.3 on 2024-08-10 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("finances", "0001_initial"),
        ("leaseAgreements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreminder",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_reminders",
                to="leaseAgreements.leaseagreement",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="finances.expense",
            ),
        ),
        migrations.AddField(
            model_name="rentpayment",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rent_payments",
                to="leaseAgreements.leaseagreement",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="finances.rentpayment",
            ),
        ),
    ]
