# Generated by Django 5.0.6 on 2024-07-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                default="estate_photos/default.jpg", upload_to="estate_photos/"
            ),
        ),
    ]
